### ISSUE TITLE
Handling multiple database connections

### ISSUE THREAD

**Issue by jasonwilson** [mikro-orm/nestjs#24] opened 2021-05-02 01:13 UTC
**Is your feature request related to a problem? Please describe.**
Looking for examples on how to handle multiple postgres database connections with NestJS. 

**Describe alternatives you've considered**
Tried initializing multiple MikroORM modules but there doesn't seem a clear way to specify the database name (only schema) on the model. 

```ts
@Module({
  imports: [ConfigModule.forRoot(),
  MikroOrmModule.forRoot({
    entities: ['./dist/entities/*'],
    entitiesTs: ['./src/entities/!(*.spec).ts'],
    dbName: 'foo"
    type: 'postgresql',
    password: ...
    host: ...
  }),
  MikroOrmModule.forRoot({
    entities: ['./dist/entities/*'],
    entitiesTs: ['./src/entities/!(*.spec).ts'],
    dbName: 'bar',
    type: 'postgresql',
    password: ...
    host: ...
  }),
```

**Additional context**
N/A

**Comment by B4nan** [comment] 2021-05-02 08:48
> Tried initializing multiple MikroORM modules but there doesn't seem a clear way to specify the database name (only schema) on the model.

There is no way to say "this entity belongs to this database" (from the entity perspective), it sounds like a bad design to me (yes, I know typeorm does it that way, just like many other things I consider bad 🤷). I really don't see why we should tie entities to particular database (from the entity def standpoint), this should be controlled from the other way around. Feel free to try to change my mind, maybe I just don't know the use case :] But if you really want to go that way, why don't you use different folders for such entities, so you can just change the paths in ORM config? Why should such entities be mixed in your app?

Also this is already possible, there is "connection name" in the ORM options if you want. This can't work just based on db names, as you might want to have multiple ORM connections to the same database as well (but with different schemas). Or even have the same database name, but on different servers/drivers. 

The missing part is the support in nest adapter, so moving to that repo. 

Currently you can get around this basically by reimplementing the adapter, it's might sound harder than it is, but all the adapter does is to register the ORM, EM and repositories, and registeres the request context helper - which already supports having multiple EM instances stored per request. See #20 for some ideas (but keep in mind that it is needed to have request context).

Will close this as it is a duplicate of #20. But feel free to continue discussion here, #20 should help already if you need to have this ASAP. I am plannig to add the support later when v5 will be getting closer to RC (but will be happy to accept PR sooner, it should be mainly about the decorator for EM injection and adjusting the request context usage with multiple EMs).

**Closed by B4nan** 2021-05-02 08:48 UTC
