### ISSUE TITLE
reflect MultiRequestContext for nestjs

### ISSUE THREAD

**Issue by muradm** [mikro-orm/nestjs#11] opened 2020-11-11 18:28 UTC
There is a fresh [enhancement-872](https://github.com/mikro-orm/mikro-orm/issues/872) which adds `MultiRequestContext`. Do you have a plan to reflect its impact for nestjs? I.e. how multiple instances could be used under nestjs?

**Comment by B4nan** [comment] 2021-01-22 09:02
It should be possible to use it right now, by disabling the automatic context middleware (`registerRequestContext: false`) and creating your own, where you use the `MultiRequestContext` instead.

**Comment by B4nan** [comment] 2021-05-02 08:50
Closing as duplicate of #20, let's track this there.

**Closed by B4nan** 2021-05-02 08:50 UTC
Labels: enhancement
