### ISSUE TITLE
Fastify adapter is not creating request contexts for POST requests

### ISSUE THREAD

**Issue by Mitch-i** [mikro-orm/nestjs#47] opened 2021-12-15 08:49 UTC
**Describe the bug**
Fastify adapter is not creating request contexts for POST requests.

```
getContext(validate = true) {
        let em = utils_1.TransactionContext.getEntityManager(); // prefer the tx context
        if (!em) {
            // no explicit tx started
            em = this.useContext ? (this.config.get('context')(this.name) || this) : this;
        }

        if (validate && this.useContext && em.id === 1 && !this.config.get('allowGlobalContext')) {
            throw errors_1.ValidationError.cannotUseGlobalContext(em.id);
        }
        return em;
}
```

and

    
```
static cannotUseGlobalContext(id) {
    return new ValidationError(id +  'Using global EntityManager instance methods for context specific actions is disallowed. If you need to work with the global instance\'s identity map, use `allowGlobalContext` configuration option or `fork()` instead.');
}
```

Console output is: '1 Using global EntityManager instance methods for context specific actions is disallowed.'

**To Reproduce**

clone https://github.com/Mitch-i/nest-mikro-rom
change config
npm i
npm run dev

curl -XPOST -d '{ "birthday": "2021-12-14", "email": "string@mail.com", "firstName": "string", "lastName": "string", "password": "string", "token": ""}' -H "Content-Type: application/json" localhost:3000/api/users/test

**Expected behavior**
To work as expected without message:  If you need to work with the global instance's identity map, use `allowGlobalContext` configuration option or `fork()

**Versions**
@mikro-orm/core: ^5.0.0-dev.562,
@mikro-orm/migrations: ^5.0.0-dev.562,
@mikro-orm/mysql: ^5.0.0-dev.562,
@mikro-orm/nestjs: ^4.3.1,
@mikro-orm/reflection: ^5.0.0-dev.562,
@mikro-orm/sql-highlighter: ^1.0.1,
@nestjs/common: ^8.2.3,
@nestjs/config: ^1.1.5,
@nestjs/core: ^8.2.3,
@nestjs/event-emitter: ^1.0.0,
@nestjs/mapped-types: *,
@nestjs/platform-express: ^8.2.3,
@nestjs/platform-fastify: ^8.2.3,
bcrypt: ^5.0.1,
mysql2: ^2.3.3,
reflect-metadata: ^0.1.13

**Comment by B4nan** [comment] 2021-12-15 09:00
side note: if you say "all latest" in the versions part, you are doing it very wrong. you should put the exact versions you are using. how can i know what does latest mean? latest master? latest 4.x version? latest stable? and if i release new version tomorrow, will that mean it was latest stable yesterday? 

it needs to be exact versions, so we get the same information even when we get to the issue in several months.

anyway, you already created the very same issue, this is duplicate of #46, the error in v4 was different, but with the same cause. i will keep this one as here we actually have proper reproduction.

**Comment by Mitch-i** [comment] 2021-12-15 13:23
#https://github.com/mikro-orm/nestjs/issues/31

**Closed** 2021-12-15 15:01 UTC

**Comment by oznakn** [comment] 2022-01-06 02:51
Hello,

Apparently, fastify's body-parser middleware loses the AsyncResource context while parsing the POST data. NestJS uses `fastify-formbody` package under the hood, and that one uses Node's `querystring` package. While the POST data is being parsed, the AsyncResource context has been lost.

Here is a simple patch that I wrote to overcome this problem.

```ts
import { AsyncResource } from 'async_hooks';
import { HttpAdapterHost } from '@nestjs/core';

import type { FastifyAdapter } from '@nestjs/platform-fastify';

export class AppModule {
  constructor(adapterHost: HttpAdapterHost<FastifyAdapter>) {
    adapterHost.httpAdapter?.getInstance()
      .addHook('onRequest', (req, _res, done) => {
        req.ctx = new AsyncResource('FastifyNestJSMikroORM');
        done();
      })
      .addHook('preValidation', (req, _res, done) => {
        req.ctx.runInAsyncScope(done);
      });
  }
}
```

Although this is not something related to MikroORM, I thought that sharing a simple solution for the problem can be something useful.
