### ISSUE TITLE
Nestjs + Fastify You cannot call em.flush() from inside lifecycle hook handlers

### ISSUE THREAD

**Issue by Mitch-i** [mikro-orm/nestjs#46] opened 2021-12-11 18:40 UTC
I have the same issue https://github.com/mikro-orm/mikro-orm/issues/627 if

```
// logs.service.ts
import { EntityRepository } from '@mikro-orm/core'
import { InjectRepository } from '@mikro-orm/nestjs'
@InjectRepository(Log) private readonly logsRepository: EntityRepository<Log>    // problem

  async createLog (createLogDto: CreateLogDto) {
    const row = await this.logRepository.create(createLogDto)
    await this.logRepository.persistAndFlush(row)  // here

    return row
  }
```
And no issue if use custom repository

```
// log.repository.ts
import { Repository } from '@mikro-orm/core'
import { EntityRepository } from '@mikro-orm/mysql'

import { Log } from '../entities/log.entity'

@Repository(Log)
export class LogRepository extends EntityRepository<Log> {}
```
```
// logs.service.ts
import { LogRepository } from './repositories/log.repository'
import { Log } from './entities/log.entity'
private readonly logRepository: LogRepository   // no problem
```

```
//log.entity.ts
@Entity({ tableName: 'log' })
export Log extends BaseEntity<Log, 'id'> {
   ***
  [EntityRepositoryType]?: UserRepository
}
```

PS: in user module works well in custom logger module to database don't work

**Comment by B4nan** [comment] 2021-12-11 18:47
Please dont ignore the issue template - what versions are you using? Ideally provide full repro.

**Comment by Langstra** [comment] 2021-12-13 12:10
This does not sound like a bug, but more like a limitation of the current implementation. It is also in the documenation: https://mikro-orm.io/docs/lifecycle-hooks/#limitations-of-lifecycle-hooks

**Comment by B4nan** [comment] 2021-12-15 09:00
duplicate of #47, keeping the new issue as this one has no reproduction.

**Closed by B4nan** 2021-12-15 09:00 UTC
